### ISSUE TITLE
Display more than 8 results

### ISSUE THREAD

**Issue by SuperSandro2000** [hsjobeki/noogle#4]
When only displaying 8 results per page, you can't really search through all your search results to find exactly what you want. I would propose to increase the default and maybe add a view which just display everything.
Also the pager is not nice to use. It only displays the first, last, current and current-1 and current+1. If you want to navigate from the 7th to the 20th page you need to click a lot.

**Comment by hsjobeki** [comment]
I‘ll add a select field where you can select the number of results per page. But i would like to leave the pagination (you called it pacer) as it is.
Because why would you want to go to 20th page to find your result there. I have to stay compatible with mobile devices and cannot just add more entries there, as it is already very dense on small devices

the other features will be added very soon

**Comment by hsjobeki** [comment]
Fixed in #8
